[package]
name = "bevy-steamworks"
version = "0.11.0"
authors = ["james7132 <contact@jamessliu.com>"]
edition = "2021"
description = "A Bevy plugin for integrating with the Steamworks SDK."
repository = "https://github.com/HouraiTeahouse/bevy-steamworks"
license = "MIT OR Apache-2.0"
keywords = ["bevy", "gamedev", "steam"]

[features]
default = []
serde = ["steamworks/serde"]

[dependencies]
bevy_log = "0.14"
bevy_app = "0.14"
bevy_ecs = "0.14"
bevy_utils = "0.14"
steamworks = { git = "https://github.com/Noxime/steamworks-rs.git", rev = "60f95358df5f7de864f5bbdad6ea748cc4e6b0a9" }

[dev-dependencies]
bevy = "0.14"
